### ISSUE TITLE
tech.pegasys.jblst 如何下载依赖

### ISSUE THREAD

**Issue by jc0803kevin** [vijay114/Filecoin-Java-Implementation#1]
这个依赖可以在哪里下载啊
<dependency>
            <groupId>tech.pegasys</groupId>
            <artifactId>jblst</artifactId>
            <version>0.3.6-4</version>
        </dependency>

大佬，可以加个联系方式，咨询一下么？

**Comment by vijay114** [comment]
You can find the mentioned dependency at https://github.com/ConsenSys/jblst
You may email me at vijaypratapsingh114@gmail.com
